# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'

    - name: Test
      run: go test -v ./collector


    - name: Build
      run: |
        GOOS=${{ matrix.os }}
        GOARCH=${{ matrix.arch }} 
        go build -o exoscale-exporter-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref }} -v ./

    - name: Extract tag name
      id: tag
      run: |
        echo ::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: Upload artifact
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: exoscale-exporter-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.tag.outputs.RELEASE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}